language: node_js
node_js: stable
script:
  - echo hello
  - npm run build
deploy:
  provider: page
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
local-dir: /dist